apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-dynamic
reclaimPolicy: retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ebs-dynamic
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ebs-sc
#   resources:
#     requests:
#       storage: 4Gi
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: ebs-dynamic
#   labels: 
#     purpose: ebs-dynamic
# spec:
#   nodeSelector:
#     topology.kubernetes.io/zone: us-east-1a  # specifying region where to your pod should go..
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:  # docekr run -v hostpath:containserpath
#     - name: ebs-dynamic
#       mountPath: /usr/share/nginx/html
#   volumes:
#   - name: ebs-dynamic
#     persistentVolumeClaim:
#       claimName: ebs-dynamic
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx
# spec:
#   type: LoadBalancer
#   selector:
#     purpose: ebs-dynamic
#   ports:
#   - name: nginx-server-port
#     protocol: TCP
#     port: 80 #service port
#     targetPort: 80 #container port
#     nodePort: 30003