apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
  - name: nginx-server
    image: nginx
    resources:
      requests:
        memory: 68Mi
        cpu: 100m        
      limits:
        memory: 100Mi
        cpu: 120m
        