#2nd method to get all the values
apiVersion: v1
kind: Pod
metadata:
  name: pod-config-2
spec:
  containers:
  - name: nginx-server
    image: nginx
    envFrom:
    - configMapRef:
        name: config-map-info    