apiVersion: v1
kind: Pod
metadata:
  name: pod-config-1
spec:
  containers:
  - name: nginx-server
    image: nginx
    env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: config-map-info  # name of the config map, it will get values from there
            key: course_name  # env.name and config map key name no need to be same
      - name: trainser
        valueFrom:
          configMapKeyRef:
            name: config-map-info
            key: trainser_name
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: config-map-info
            key: total_duration 