kind: Service
apiVersion: v1
metadata:
  name: nginx-cluster-ip-service
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-server-port
    protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port